# Generated by Django 4.2.20 on 2025-03-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unite', '0002_alter_unite_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unite',
            name='designation',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
