# Generated by Django 4.2.20 on 2025-03-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_alter_employee_email_alter_employee_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('Actif', 'Actif'), ('Non Actif', 'Non Actif')], default='active', help_text="Statut de l'agent", max_length=20, null=True),
        ),
    ]
