# Generated by Django 4.2.20 on 2025-03-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('Actif', 'Actif'), ('Non Actif', 'Non Actif')], default='Actif', help_text="Statut de l'agent", max_length=20, null=True),
        ),
    ]
