"""
Django settings for Gestion_Personnel_INRAP project.
Generated by 'django-admin startproject' using Django 4.2.18.
For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cg8x7jn$#c+k5^9#xw1g4#xrc+!41a%p83=+*78dw0w6fn-=i='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'OrganizationalUnit',
    'fonction', 
    'specialite',
    'unite', 
    'Employee',
    'RespensableOrganisationUnite',
    'Stagiaire',
    'Conge',
    'Activation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
   # 'Activation.activation_middleware.ActivationMiddleware',
]

ROOT_URLCONF = 'Gestion_Personnel_INRAP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Gestion_Personnel_INRAP.wsgi.application'
"""    
# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
 """
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Gestion_Personnel_INRAP_db',  # Remplace par le nom de ta base
        'USER': 'root',  # Par défaut dans XAMPP
        'PASSWORD': '',  # Laisse vide si aucun mot de passe
        'HOST': 'localhost',  
        'PORT': '3306',  
          'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []
STATIC_ROOT = BASE_DIR / "staticfiles"

# Collect static files command: python manage.py collectstatic --noinput

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'transactions.log',
            'formatter': 'detailed',
        },
    },
    'formatters': {
        'detailed': {
            'format': '{asctime} - {levelname} - {module} - {message}',
            'style': '{',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'transactions': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Hidden Imports for PyInstaller
hiddenimports = [
    'Conge.context_processors', 
    'fonction.templatetags', 
    'Employee.templatetags', 
    'django.contrib.staticfiles.context_processors',
    'Activation.context_processors',
    'fonction.context_processors',
    'specialite.templatetags',
    'django.contrib.admin.context_processors',
    'django.contrib.messages.templatetags',
    'specialite.context_processors',
    'Stagiaire.templatetags',
    'Activation.templatetags',
    'django.contrib.sessions.templatetags',
    'Employee.context_processors',
    'django.contrib.sessions.context_processors',
    'django.contrib.staticfiles.templatetags',
    'unite.context_processors',
    'Conge.templatetags',
    'django.contrib.contenttypes.context_processors',
    'unite.templatetags',
    'django.contrib.auth.templatetags',
    'OrganizationalUnit.context_processors',
    'OrganizationalUnit.templatetags',
    'Stagiaire.context_processors',
    'RespensableOrganisationUnite.templatetags',
    'django.contrib.contenttypes.templatetags',
    'RespensableOrganisationUnite.context_processors'
]
