# Generated by Django 4.2.20 on 2025-03-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialite',
            name='designation',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
